version: '3.5'

services:
  redis:
    container_name: cache
    image: redis
    expose:
      - 6379
    #ports:
    #  - '6379:6379'

  service:
    #image: pimpbot9000/4-tram-service
    build: .
    container_name: tram-service
    ports:
      - 4000:3000    
    environment:
      - REDIS_HOST=redis
