version: '3.5'

services:
  redis:
    container_name: cache
    image: redis
    expose:
      - 6379   

  service:
    build: .   
    container_name: tram-service
    ports:
      - 4000:3000    
    environment:
      - REDIS_HOST=redis
