version: 2.1
orbs:
  docker: circleci/docker@1.5.0
  heroku: circleci/heroku@1.2.4
 

workflows:
  docker_and_heroku:
    jobs:
      - docker/publish:
            image: pimpbot9000/4-tram-service
            tag: 'latest'
      - heroku/deploy-via-git:
            #requires:
            #  - docker/publish
            filters:
              branches:
                only: master 